# EXAMPLE:
# common:
#   admin_email: admin@domain.com
#   xml_rpc_url: http://domain.com:8000/
#   media_path: <%= Rails.root %>/tmp/media
# 
# development:
#   xml_rpc_url: http://localhost:8000/
# 
# test:
#   xml_rpc_url: http://localhost:8008/

common:
  s3:
    bucket: social-devotional
    credentials:
      access_key_id: AKIAJAW4PTOXOO6POA7Q
      secret_access_key: 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

development:

test:

production:

#custom_environment: