# EXAMPLE:
# common:
#   admin_email: admin@domain.com
#   xml_rpc_url: http://domain.com:8000/
#   media_path: <%= Rails.root %>/tmp/media
# 
# development:
#   xml_rpc_url: http://localhost:8000/
# 
# test:
#   xml_rpc_url: http://localhost:8008/

common:
  dev_user: developer
  dev_pass: developer
  domains:
    media: media.socialdevotional.com
    cdn: www.socialdevotional.com
    origin: origin.socialdevotional.com
  s3:
    bucket: social-devotional
    credentials:
      access_key_id: AKIAJAW4PTOXOO6POA7Q
      secret_access_key: 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
  redis:
    host: 'localhost'
    port: 6379
    timeout: 2
    pool: 5
  crawler_user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36' #http://www.useragentstring.com/pages/All/

development:

test:

production:
  redis:
    host: 'redis-master.socialdevotional.com'
    pool: 10

#custom_environment: