# EXAMPLE:
# common:
#   admin_email: admin@domain.com
#   xml_rpc_url: http://domain.com:8000/
#   media_path: <%= Rails.root %>/tmp/media
# 
# development:
#   xml_rpc_url: http://localhost:8000/
# 
# test:
#   xml_rpc_url: http://localhost:8008/

common:
  fog_credentials:
    aws_access_key_id: '<your aws_access_key_id>'
    aws_secret_access_key: '<your aws_secret_access_key>'
    provider: 'AWS'
    region: 'eu-west-1'

development:

test:

production:

#custom_environment: